version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/react

hooks:
  BeforeInstall:
    - location: scripts/stop_containers.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_containers.sh
      timeout: 300
      runas: ubuntu

